### ISSUE TITLE
Uncaught require(): module not found: MySocket

### ISSUE THREAD

**Issue by markosole** [solisoft/FuseSocketTCP#2]
Hi, I am new to fuse and trying to figure out and solve problem with socket.io. I am getting this error when I use Your project and try to build it. 
[Viewport]: Error: : Error message: Uncaught require(): module not found: MySocket

**Comment by solisoft** [comment]
This lib is for Raw TCP communication to a TCP server, not websockets
I wrote it for a previous version of Fuse, I have to check if it is still woking with latest one.

**Comment by markosole** [comment]
Yep I understand, that's what I need at the first place. It does not work on latest Fuse 1.2.1. Few errors were thrown. 
```
Uno.Platform2.Application.Terminating += OnTerminating;
``` 
I had to comment that line. Platform2 is not in use any more.  File> WebSocketModule.uno  and all other files where Platform2 is used.

**Comment by solisoft** [comment]
You can create a PR if you want ... or wait until I fix it but not too much
available right now

**Comment by markosole** [comment]
No problem, I will keep eyes on this, when ya find a time to test it again. I am still looking (for working sample) for a solution. I have tried to implement socket.io but it did not work. Again, on latest Fuse 1.2.1. 
Thanks.

**Comment by solisoft** [comment]
@markosole I just test it on my Fuse 1.2.1 ... Finally I just had to use Uno.UX.Resource instead of Resource to make it work.

To run it, clone this repository, then run the TCP server with `node echo_srv.js` then run `fuse preview` ... working fine on my laptop.
![capture d ecran 2017-09-04 15 25 56](https://user-images.githubusercontent.com/6237/30026396-5fa9d9d6-9185-11e7-8746-3c50956ca6e1.jpg)
